languageCode = "en-us"
theme = "azodn"
pluralizelisttitles = false
summaryLength = 70
googleAnalytics = ""
defaultContentLanguage = "en"
title = "Arizona Organization Development Network"
paginate = 10
email = "test"
baseurl = "https://azodn.org"

[params]
logo_text = "AZODN"
mainSections = ["events"]
copyright = "Copyright (c) 2023, AZODN - all rights reserved"
date_format = "January 2, 2006"
privacy_policy = "true"
defaultKeywords = ["azodn"]
author = "Colbal"
logo = "img/logo-small.png"
disabled_logo = false
about_us = "<p>AZODN exists to elevate individuals and organizations to their highest potential.</p>"
contact_url = "/contact"
style = "azodn"
logo_small = "img/logo.png"
viewMorePostLink = "/events/"
address = ""
defaultDescription = "AZODN exists to elevate individuals and organizations to their highest potential."
dropdown_mouse_over = false
email = "info@azodn.org"

[params.see_more]
enable = true
icon = "fas fa-link"
title = "Become a member"
subtitle = "Our members are a diverse group of professionals who value meaningful connections, sharing powerful ideas and continued professional development."
link_url = "/join-us"
link_text = "annual membership"

[params.home-hero]

[params.recent_posts]
enable = true
title = "Events"
subtitle = ""
hide_summary = true

[params.widgets]
categories = true
tags = true
search = true

[params.footer]

[params.footer.recent_posts]
enable = false

[params.topbar]
enable = true
text = "<p class=\"\">Contact us at info@azodn.org.</p> <!--\n       <a href=\"mailto:info@azodn.org\" data-animate-hover=\"pulse\"><i class=\"fas fa-envelope\"></i></a>\n      </p> -->\n      "

[permalinks]
blog = "/events/:year/:month/:day/:filename/"

[taxonomies]
category = "categories"
tag = "tags"
author = "authors"

[menu]

[[menu.main]]
name = "Home"
identifier = "menu.home"
url = "/"
weight = 10

[[menu.main]]
name = "Events"
url = "/events"
weight = 20

[[menu.main]]
name = "Join Us"
url = "/join-us"
weight = 30

[[menu.main]]
name = "CODA"
url = "/coda"
weight = 40

[[menu.main]]
name = "About"
identifier = "menu.about"
url = "/about"
weight = 50

[[menu.main]]
name = "What we do"
url = "/about/what-we-do"
weight = 51
parent = "menu.about"

[[menu.main]]
name = "Who we are"
url = "/about/who-we-are"
weight = 52
parent = "menu.about"

[[menu.main]]
name = "FAQ"
url = "/about/faq"
weight = 59
parent = "menu.about"

[[menu.topbar]]
weight = 20
name = "Email"
url = "mailto:info@azodn.org"
pre = "<i class='fas fa-2x fa-envelope'></i>"

[[menu.topbar]]
weight = 30
name = "YouTube"
url = "https://www.youtube.com/@AZODN-ORG"
pre = "<i class='fab fa-2x fa-youtube'></i>"

[[menu.topbar]]
weight = 40
name = "Facebook"
url = "https://www.facebook.com/groups/1121395861295634/"
pre = "<i class='fab fa-2x fa-facebook'></i>"