baseurl = "https://imaginative-pastelito-32138a.netlify.app/" # chang once live
title = "Arizona Organization Development Network"
theme = "azodn"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
paginate = 10

# not pluralize title pages by default
pluralizelisttitles = false

[menu]

# Main menu
[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 10
[[menu.main]]
    name       = "Events"
    url        = "/events"
    weight     = 20
[[menu.main]]
    name       = "Join Us"
    url        = "/join-us"
    weight     = 30
[[menu.main]]
    name       = "CODA"
    url        = "/coda"
    weight     = 40
[[menu.main]]
    name       = "About"
    identifier = "menu.about"
    url        = "/about"
    weight     = 50
[[menu.main]]
    name       = "What we do"
    url        = "/about/what-we-do"
    weight     = 51
    parent     = "menu.about"
[[menu.main]]
    name       = "Who we are"
    url        = "/about/who-we-are"
    weight     = 52
    parent     = "menu.about"
[[menu.main]]
    name       = "FAQ"
    url        = "/about/faq"
    weight     = 59
    parent     = "menu.about"
    
# TODO clean out unused items

# [[menu.main]]
#     name       = "Option 1: Default Page"
#     url        = "/"
#     weight     = 1
#     parent     = "menu.home"

# [[menu.main]]
#     name       = "Option 2: Application"
#     url        = "/"
#     weight     = 2
#     parent     = "menu.home"

# [[menu.main]]
#     name       = "Option 3: Startup"
#     url        = "/"
#     weight     = 3
#     parent     = "menu.home"

# [[menu.main]]
#     name       = "Option 4: Agency"
#     url        = "/"
#     weight     = 4
#     parent     = "menu.home"

# [[menu.main]]
#     name       = "Option 5: Portfolio"
#     url        = "/"
#     weight     = 5
#     parent     = "menu.home"

# [[menu.main]]
#     name       = "Features"
#     identifier = "menu.features"
#     url        = "/img/template-easy-customize.png"
#     weight     = 3

# [[menu.main]]
#     name       = "Shortcodes"
#     identifier = "section.shortcodes"
#     url        = ""
#     weight     = 1
#     parent     = "menu.features"
#     post       = 1

# [[menu.main]]
#     name       = "Header variations"
#     identifier = "section.headervariations"
#     url        = ""
#     weight     = 2
#     parent     = "menu.features"
#     post       = 2

# [[menu.main]]
#     name       = "Accordions"
#     url        = ""
#     weight     = 1
#     parent     = "section.shortcodes"

# [[menu.main]]
#     name       = "Alerts"
#     url        = ""
#     weight     = 2
#     parent     = "section.shortcodes"

# [[menu.main]]
#     name       = "Buttons"
#     url        = ""
#     weight     = 3
#     parent     = "section.shortcodes"

# [[menu.main]]
#     name       = "Content Boxes"
#     url        = ""
#     weight     = 4
#     parent     = "section.shortcodes"

# [[menu.main]]
#     name       = "Horizontal Blocks"
#     url        = ""
#     weight     = 5
#     parent     = "section.shortcodes"

# [[menu.main]]
#     name       = "Pagination"
#     url        = ""
#     weight     = 6
#     parent     = "section.shortcodes"

# [[menu.main]]
#     name       = "Tabs"
#     url        = ""
#     weight     = 7
#     parent     = "section.shortcodes"

# [[menu.main]]
#     name       = "Typography"
#     url        = ""
#     weight     = 8
#     parent     = "section.shortcodes"

# [[menu.main]]
#     name       = "Default Sticky Header"
#     url        = ""
#     weight     = 1
#     parent     = "section.headervariations"

# [[menu.main]]
#     name       = "No Sticky Header"
#     url        = ""
#     weight     = 2
#     parent     = "section.headervariations"

# [[menu.main]]
#     name       = "Light Header"
#     url        = ""
#     weight     = 3
#     parent     = "section.headervariations"

# [[menu.main]]
#     name       = "Portfolio"
#     identifier = "menu.portfolio"
#     url        = "/img/template-homepage.png"
#     weight     = 3

# [[menu.main]]
#     name       = "Portfolio"
#     identifier = "section.portfolio"
#     url        = ""
#     weight     = 1
#     parent     = "menu.portfolio"
#     post       = 1

# [[menu.main]]
#     name       = "2 Columns"
#     url        = ""
#     weight     = 1
#     parent     = "section.portfolio"

# [[menu.main]]
#     name       = "2 Columns With Negative Space"
#     url        = ""
#     weight     = 2
#     parent     = "section.portfolio"

# [[menu.main]]
#     name       = "3 Columns"
#     url        = ""
#     weight     = 3
#     parent     = "section.portfolio"

# [[menu.main]]
#     name       = "3 Columns With Negative Space"
#     url        = ""
#     weight     = 4
#     parent     = "section.portfolio"

# [[menu.main]]
#     name       = "4 Columns"
#     url        = ""
#     weight     = 5
#     parent     = "section.portfolio"

# [[menu.main]]
#     name       = "4 Columns With Negative Space"
#     url        = ""
#     weight     = 6
#     parent     = "section.portfolio"

# [[menu.main]]
#     name       = "Portfolio - detail"
#     url        = ""
#     weight     = 7
#     parent     = "section.portfolio"

# [[menu.main]]
#     name       = "Portfolio - detail 2"
#     url        = ""
#     weight     = 8
#     parent     = "section.portfolio"

# [[menu.main]]
#     name       = "About"
#     identifier = "section.about"
#     url        = ""
#     weight     = 2
#     parent     = "menu.portfolio"
#     post       = 2

# [[menu.main]]
#     name       = "About Us"
#     url        = ""
#     weight     = 1
#     parent     = "section.about"

# [[menu.main]]
#     name       = "Our Team"
#     url        = ""
#     weight     = 2
#     parent     = "section.about"

# [[menu.main]]
#     name       = "Marketing"
#     identifier = "section.marketing"
#     url        = ""
#     weight     = 3
#     parent     = "menu.portfolio"
#     post       = 2

# [[menu.main]]
#     name       = "Packages"
#     url        = ""
#     weight     = 1
#     parent     = "section.marketing"

# [[menu.main]]
#     name       = "All Pages"
#     identifier = "menu.allpages"
#     url        = ""
#     weight     = 4

# [[menu.main]]
#     name       = "Home"
#     identifier = "section.ap-home"
#     url        = ""
#     weight     = 1
#     parent     = "menu.allpages"
#     post       = 1

# [[menu.main]]
#     name       = "About"
#     identifier = "section.ap-about"
#     url        = ""
#     weight     = 2
#     parent     = "menu.allpages"
#     post       = 1

# [[menu.main]]
#     name       = "Marketing"
#     identifier = "section.ap-marketing"
#     url        = ""
#     weight     = 3
#     parent     = "menu.allpages"
#     post       = 1

# [[menu.main]]
#     name       = "Portfolio"
#     identifier = "section.ap-portfolio"
#     url        = ""
#     weight     = 1
#     parent     = "menu.allpages"
#     post       = 2

# [[menu.main]]
#     name       = "User Pages"
#     identifier = "section.ap-userpages"
#     url        = ""
#     weight     = 2
#     parent     = "menu.allpages"
#     post       = 2

# [[menu.main]]
#     name       = "Shop"
#     identifier = "section.ap-shop"
#     url        = ""
#     weight     = 1
#     parent     = "menu.allpages"
#     post       = 3

# [[menu.main]]
#     name       = "Shop - Order Process"
#     identifier = "section.ap-shoporderprocess"
#     url        = ""
#     weight     = 2
#     parent     = "menu.allpages"
#     post       = 3

# [[menu.main]]
#     name       = "Contact"
#     identifier = "section.ap-contact"
#     url        = ""
#     weight     = 1
#     parent     = "menu.allpages"
#     post       = 4

# [[menu.main]]
#     name       = "Pages"
#     identifier = "section.ap-pages"
#     url        = ""
#     weight     = 2
#     parent     = "menu.allpages"
#     post       = 4

# [[menu.main]]
#     name       = "Blog"
#     identifier = "section.ap-blog"
#     url        = "/blog/"
#     weight     = 3
#     parent     = "menu.allpages"
#     post       = 4

# [[menu.main]]
#     name       = "Blog Listing Big"
#     url        = "/blog/"
#     weight     = 1
#     parent     = "section.ap-blog"

# [[menu.main]]
#     name       = "Blog"
#     identifier = "menu.blog"
#     url        = "/blog/"
#     weight     = 5

# [[menu.main]]
#     name       = "FAQ"
#     identifier = "menu.faq"
#     url        = "/faq/"
#     weight     = 6

# [[menu.main]]
#     identifier = "contact"
#     name       = "Contact"
#     url        = "/contact/"
#     weight     = 7


# Top bar social links menu (right side)

# [[menu.topbar]]
#     weight = 10
#     name = "Phone"
#     url = "tel:+12 34 567 89 01"
#     pre = "<i class='fas fa-2x fa-phone'></i>"
[[menu.topbar]]
    weight = 20
    name = "Email"
    url = "mailto:info@azodn.org"
    pre = "<i class='fas fa-2x fa-envelope'></i>"
[[menu.topbar]]
    weight = 30
    name = "YouTube"
    url = "https://www.youtube.com/@AZODN-ORG"
    pre = "<i class='fab fa-2x fa-youtube'></i>"
[[menu.topbar]]
    weight = 40
    name = "Facebook"
    url = "https://www.facebook.com/groups/1121395861295634/"
    pre = "<i class='fab fa-2x fa-facebook'></i>"

[params]
    email = "info@azodn.org"
    viewMorePostLink = "/events/"
    author = "Colbal"
    defaultKeywords = ["azodn",]
    mainSections = ["events"]
    defaultDescription = "AZODN exists to elevate individuals and organizations to their highest potential."
    

    # Social media
    # facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    # twitter_site = "GoHugoIO" # the Twitter handle of your site (without the '@')
    # default_sharing_image = "img/sharing-default.png"

    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    # enableGoogleMaps = true
    # googleMapsApiKey = "AIzaSyAv7Sza8NSp9_l_g8G2vlo0H4ydEPn_2jY"

    # latitude = "-12.043333"
    # longitude = "-77.028333"

    style = "azodn"

    about_us = "<p>AZODN exists to elevate individuals and organizations to their highest potential.</p>"
    copyright = "Copyright (c) 2023, AZODN - all rights reserved."
    privacy_policy = "true" # TODO code this into the footer and test

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    dropdown_mouse_over = false

    disabled_logo = false
    logo_text = "AZODN"

    logo = "img/logo-small.png"
    logo_small = "img/logo.png"
    contact_url = "/contact"
    address = "" #"
    # <p class="text-uppercase"><strong>Universal Ltd.</strong>
    #     <br>13/25 New Avenue
    #     <br>Newtown upon River
    #     <br>45Y 73J
    #     <br>England
    #     <br>
    #     <strong>Great Britain</strong>
    #   </p>
    #   """

[permalinks]
    blog = "/events/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="">Contact us at info@azodn.org.</p> <!--
       <a href="mailto:info@azodn.org" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p> -->
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

# [params.carouselCustomers]
#     items = 6
#     auto_play = false
#     slide_speed = 2000
#     pagination_speed = 1000

# [params.carouselTestimonials]
#     items = 4
#     auto_play = false
#     slide_speed = 2000
#     pagination_speed = 1000

# [params.carouselHomepage]
#     # All carousel items are defined in their own files. You can find example items
#     # at 'exampleSite/data/carousel'.
#     # For more information take a look at the README.
#     enable = true
#     auto_play = true
#     slide_speed = 2000
#     pagination_speed = 1000

# [params.features]
#     enable = true
#     cols = 3 # Default: 3, Available values 2,3,4,6
#     # All features are defined in their own files. You can find example items
#     # at 'exampleSite/data/features'.
#     # For more information take a look at the README.

# [params.testimonials]
#     enable = true
#     # All testimonials are defined in their own files. You can find example items
#     # at 'exampleSite/data/testimonials'.
#     # For more information take a look at the README.
#     title = "Testimonials"
#     subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

# build this out so that the clint only have to change it here and it will reflect on the main page
[params.home-hero]
# hero_image = "img/test.webp"
# hero_text = "Test hero text"
# declaration = "Test declaration text"
# call_to_action = "Test call to action text"
# button_text = "Button"

[params.recent_posts]
    enable = true
    title = "Events"
    subtitle = ""
    hide_summary = true

[params.see_more]
    enable = true
    icon = "fas fa-link"
    title = "Become a member"
    subtitle = "Our members are a diverse group of professionals who value meaningful connections, sharing powerful ideas and continued professional development."
    link_url = "/join-us"
    link_text = "annual membership"

[params.footer.recent_posts]
    enable = false

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"
