baseurl = "https://imaginative-pastelito-32138a.netlify.app/" # chang once live
title = "Arizona Organization Development Network"
theme = "azodn"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
paginate = 10

# not pluralize title pages by default
pluralizelisttitles = false

[menu]

# Main menu
[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 10
[[menu.main]]
    name       = "Events"
    url        = "/events"
    weight     = 20
[[menu.main]]
    name       = "Join Us"
    url        = "/join-us"
    weight     = 30
[[menu.main]]
    name       = "CODA"
    url        = "/coda"
    weight     = 40
[[menu.main]]
    name       = "About"
    identifier = "menu.about"
    url        = "/about"
    weight     = 50
[[menu.main]]
    name       = "What we do"
    url        = "/about/what-we-do"
    weight     = 51
    parent     = "menu.about"
[[menu.main]]
    name       = "Who we are"
    url        = "/about/who-we-are"
    weight     = 52
    parent     = "menu.about"
[[menu.main]]
    name       = "FAQ"
    url        = "/about/faq"
    weight     = 59
    parent     = "menu.about"
    


[[menu.topbar]]
    weight = 20
    name = "Email"
    url = "mailto:info@azodn.org"
    pre = "<i class='fas fa-2x fa-envelope'></i>"
[[menu.topbar]]
    weight = 30
    name = "YouTube"
    url = "https://www.youtube.com/@AZODN-ORG"
    pre = "<i class='fab fa-2x fa-youtube'></i>"
[[menu.topbar]]
    weight = 40
    name = "Facebook"
    url = "https://www.facebook.com/groups/1121395861295634/"
    pre = "<i class='fab fa-2x fa-facebook'></i>"

[params]
    email = "info@azodn.org"
    viewMorePostLink = "/events/"
    author = "Colbal"
    defaultKeywords = ["azodn",]
    mainSections = ["events"]
    defaultDescription = "AZODN exists to elevate individuals and organizations to their highest potential."
    
    style = "azodn"

    about_us = "<p>AZODN exists to elevate individuals and organizations to their highest potential.</p>"
    copyright = "Copyright (c) 2023, AZODN - all rights reserved."
    privacy_policy = "true" # TODO code this into the footer and test

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    dropdown_mouse_over = false

    disabled_logo = false
    logo_text = "AZODN"

    logo = "img/logo-small.png"
    logo_small = "img/logo.png"
    contact_url = "/contact"
    address = "" #"
  
[permalinks]
    blog = "/events/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="">Contact us at info@azodn.org.</p> <!--
       <a href="mailto:info@azodn.org" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p> -->
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.home-hero]
# hero_image = "img/test.webp"
# hero_text = "Test hero text"
# declaration = "Test declaration text"
# call_to_action = "Test call to action text"
# button_text = "Button"

[params.recent_posts]
    enable = true
    title = "Events"
    subtitle = ""
    hide_summary = true

[params.see_more]
    enable = true
    icon = "fas fa-link"
    title = "Become a member"
    subtitle = "Our members are a diverse group of professionals who value meaningful connections, sharing powerful ideas and continued professional development."
    link_url = "/join-us"
    link_text = "annual membership"

[params.footer.recent_posts]
    enable = false

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"
