backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# These lines should *not* be indented
media_folder: "public/img/" # Media files will be stored in the repo under static/images/uploads
public_folder: "img/" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "events" # Used in routes, e.g., /admin/collections/blog
    label: "Events" # Used in the UI
    folder: "content/events" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Event Date", name: "date", widget: "datetime" }
      - {
          label: "Featured Image",
          name: "banner",
          widget: "image",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
      #end of Events collection

  - name: "pages"
    label: "Pages"
    files:
      - file: "content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image, required: false }
          - { label: SEO Description, name: description, widget: text }
        #end of Home page

      - file: "content/about/faq.md"
        label: "FAQ"
        name: "faq"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: SEO Description, name: description, widget: text }
          - { label: "Body", name: body, widget: markdown }
        # end of FAQ

      - file: "content/about/what-we-do.md"
        label: "What We Do"
        name: "what we do"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: SEO Description, name: description, widget: text }
          - { label: "Body", name: body, widget: markdown }
          # end of What We Do

      - file: "content/about/who-we-are.md"
        label: "Who We Are"
        name: "who we are"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: SEO Description, name: description, widget: text }
          - { label: "Body", name: body, widget: markdown }
          # end of Who We Are

      - file: "content/contact.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
          # end of Contact

      - file: "content/coda.md"
        label: "CODA"
        name: "coda"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image, required: false }
          - { label: Body, name: body, widget: markdown }

      - file: "content/join-us/index.md"
        label: "Join Us"
        name: "join-us"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }

  - name: "site_settings"
    label: "Site Settings"
    files:
      - file: "site/data/footer.json"
        label: Footer
        name: footer
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Blurb, name: blurb, widget: text }
      # end of footer

      - file: "config.toml"
        label: Site Config
        name: config
        editor:
          preview: false
        fields:
          - { label: Site Title for Browser Tab, name: title, widget: string }
          - {
              label: Google Analytics tracking code,
              name: googleAnalytics,
              widget: string,
              required: false,
            }
           - {
              label: Number of Posts per page,
              name: paginate,
              widget: number,
            }
